# Generated by Django 5.0.7 on 2024-07-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='types',
        ),
        migrations.AlterField(
            model_name='hobbies',
            name='hobby',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='interests',
            name='interest',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='qualifications',
            name='qualification',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
